version: '2.4'
x-net: &net
  networks:
      - main
services:
  db:
    <<: *net
    image: datajoint/mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=coogs
    # ports:
    #   - "3306:3306"
    # To persist MySQL data
    # volumes:
    #   - ./mysql/data:/var/lib/mysql
    #   - ./mysql/my.cnf:/etc/mysql/my.cnf
  app:
    <<: *net
    build:
      context: .
    image: raphaelguzman/uh_demo:0.0.0
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DJ_HOST=db
      - DJ_USER=root
      - DJ_PASS=coogs
      - PYTHON_USER=dja
      - JUPYTER_PASSWORD=coogs
      - DISPLAY
    working_dir: /home/dja
    command: >
      /bin/sh -c
       "
        # conda install -yc conda-forge datajoint;
        jupyter lab;
       "
    ports:
      - "8888:8888"
    user: 1000:anaconda
    volumes:
      - ./apk_requirements.txt:/apk_requirements.txt
      - ./pip_requirements.txt:/pip_requirements.txt
      - ./conda_requirements.txt:/conda_requirements.txt
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      # Additional mounted notebooks may go here
      - ./notebook:/home/dja/notebooks
      - ../dj-python-101/ch1:/home/dja/tutorials
networks:
  main:
# pip install --user imutils
# conda install -c conda-forge opencv=4.2.0
# apk add mesa-gl

# QT_QPA_PLATFORM_PLUGIN_PATH=/opt/conda/pkgs/qt-5.9.7-h52cfd70_2/plugins python neural_style_transfer.py --image images/giraffe.jpg --model models/eccv16/the_wave.t7
# QT_QPA_PLATFORM_PLUGIN_PATH=/opt/conda/plugins python neural_style_transfer.py --image images/giraffe.jpg --model models/eccv16/the_wave.t7
# QT_QPA_PLATFORM_PLUGIN_PATH=/usr/lib python neural_style_transfer.py --image images/giraffe.jpg --model models/eccv16/the_wave.t7
# QT_QPA_PLATFORM_PLUGIN_PATH=/opt/conda/include python neural_style_transfer.py --image images/giraffe.jpg --model models/eccv16/the_wave.t7
# QT_QPA_PLATFORM_PLUGIN_PATH=/opt/conda/pkgs python neural_style_transfer.py --image images/giraffe.jpg --model models/eccv16/the_wave.t7
# QT_QPA_PLATFORM_PLUGIN_PATH=/opt/conda/lib python neural_style_transfer.py --image images/giraffe.jpg --model models/eccv16/the_wave.t7
# QT_QPA_PLATFORM_PLUGIN_PATH=/opt/conda/lib/pkgconfig python neural_style_transfer.py --image images/giraffe.jpg --model models/eccv16/the_wave.t7

# export QT_DEBUG_PLUGINS=1
# export LD_LIBRARY_PATH=/opt/conda/pkgs/qt-5.9.7-h52cfd70_2/plugins/platforms:$LD_LIBRARY_PATH
# export LD_LIBRARY_PATH=/opt/conda/plugins/platforms:$LD_LIBRARY_PATH

# export QT_DEBUG_PLUGINS=1
# env LANG=C ldd /opt/conda/plugins/platforms/libqxcb.so

# pip install --user Pillow

# /opt/conda/plugins/platforms # find / -name "*libqxcb.so*"
# /opt/conda/pkgs/qt-5.9.7-h52cfd70_2/plugins/platforms/libqxcb.so
# /opt/conda/plugins/platforms/libqxcb.so
# /opt/conda/plugins/platforms # ln -sf /opt/conda/pkgs/qt-5.9.7-h52cfd70_2/plugins/platforms/ /usr/bin/

# apk add libselinux