version: '2.4'
x-net: &net
  networks:
      - main
services:
  db:
    <<: *net
    image: datajoint/mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=coogs
    # ports:
    #   - "3306:3306"
    # To persist MySQL data
    # volumes:
    #   - ./mysql/data:/var/lib/mysql
    #   - ./mysql/my.cnf:/etc/mysql/my.cnf
  app:
    <<: *net
    image: raphaelguzman/jupyter:1.0.0-python3.7-alpine
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DJ_HOST=db
      - DJ_USER=root
      - DJ_PASS=coogs
      - PYTHON_USER=dja
      - JUPYTER_PASSWORD=coogs
    working_dir: /home/dja
    command: >
      /bin/sh -c
       "
        # conda install -yc conda-forge datajoint;
        jupyter lab;
       "
    ports:
      - "8888:8888"
    volumes:
      - ./apk_requirements.txt:/apk_requirements.txt
      # Additional mounted notebooks may go here
      - ./notebook:/home/dja/notebooks
      - ../dj-python-101/ch1:/home/dja/tutorials
networks:
  main: